{{-- Placeholder draft — replace with lawyer-reviewed text before going live. --}}
<h2>1. No professional advice</h2>
<p>This Service is an administrative and academic management tool. Nothing generated by it (reports, fee
calculations, notices, communications) constitutes legal, financial, tax or educational-compliance advice. The
Institute remains responsible for verifying figures and decisions before acting on them.</p>

<h2>2. "As is" service</h2>
<p>The Service is provided "as is" and "as available", without warranties of any kind, express or implied, including
fitness for a particular purpose, except as expressly stated in the Terms &amp; Conditions.</p>

<h2>3. Third-party integrations</h2>
<p>Where the Service integrates with third-party providers (payment gateways, SMS/email/WhatsApp delivery, bank
verification, etc.), we are not responsible for outages, errors or data-handling practices of those third parties
beyond our control.</p>

<h2>4. Data entered by the Institute</h2>
<p>We are not responsible for the accuracy, legality or completeness of data entered into the Service by the
Institute or its staff. The Institute is solely responsible for the content it uploads, stores and shares through
the platform.</p>

<h2>5. Force majeure</h2>
<p>We are not liable for delays or failures in the Service caused by events beyond our reasonable control, including
internet/network outages, cloud-provider outages, natural disasters, or government action.</p>

<h2>6. Limitation of liability</h2>
<p>Use of the Service is at the Institute's own risk to the extent permitted by law. Our total liability for any
claim arising from use of the Service is capped as described in the Terms &amp; Conditions.</p>
